# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x07network\"%\n\x0bJoinRequest\x12\x16\n\x0e\x63lient_address\x18\x01 \x01(\t\"!\n\x0cJoinResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\"?\n\x07Message\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xa6\x01\n\x07Network\x12\x33\n\x04Join\x12\x14.network.JoinRequest\x1a\x15.network.JoinResponse\x12/\n\x0bSendMessage\x12\x10.network.Message\x1a\x0e.network.Empty\x12\x35\n\x0fReceiveMessages\x12\x10.network.Message\x1a\x0e.network.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_JOINREQUEST']._serialized_start=26
  _globals['_JOINREQUEST']._serialized_end=63
  _globals['_JOINRESPONSE']._serialized_start=65
  _globals['_JOINRESPONSE']._serialized_end=98
  _globals['_MESSAGE']._serialized_start=100
  _globals['_MESSAGE']._serialized_end=163
  _globals['_EMPTY']._serialized_start=165
  _globals['_EMPTY']._serialized_end=172
  _globals['_NETWORK']._serialized_start=175
  _globals['_NETWORK']._serialized_end=341
# @@protoc_insertion_point(module_scope)
