# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apersistent_streaming.proto\".\n\rClientMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\rServerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tfrom_user\x18\x02 \x01(\t2u\n\x15PersistentChatService\x12\x30\n\x0eRegisterClient\x12\x0e.ClientMessage\x1a\x0e.ServerMessage\x12*\n\x04\x43hat\x12\x0e.ClientMessage\x1a\x0e.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persistent_streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CLIENTMESSAGE']._serialized_start=30
  _globals['_CLIENTMESSAGE']._serialized_end=76
  _globals['_SERVERMESSAGE']._serialized_start=78
  _globals['_SERVERMESSAGE']._serialized_end=129
  _globals['_PERSISTENTCHATSERVICE']._serialized_start=131
  _globals['_PERSISTENTCHATSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
